[[license]]

=== 许可证

Flowable 是 link:$$http://www.apache.org/licenses/LICENSE-2.0.html$$[the Apache V2 license] 许可证.

[[download]]

=== 下载

link:$$http://www.flowable.org/downloads.html$$[http://www.flowable.org/downloads.html]

[[sources]]

=== 源码

Flowable大部分由JAR包组成。源码可以在
link:$$https://github.com/flowable/flowable-engine$$[https://github.com/flowable/flowable-engine] 找到

[[required.software]]

=== 所需软件

==== JDK 8+

Flowable在高于或等于版本8的JDK上运行。
跳转至 link:$$http://www.oracle.com/technetwork/java/javase/downloads/index.html$$[Oracle Java SE downloads] 然后点击 "Download JDK"。
该页上也有安装说明。若要验证安装是非成功，可以在命令行上执行 +java -version+ 。这将会打印出已经安装的JDK版本。

==== IDE

Flowable 可以使用任意您喜欢的IDE来进行开发。
如果你想使用Flowable Designer(设计器)，则需要 Eclipse Mars 或者是 Neon 版本。
从 link:$$http://www.eclipse.org/downloads/$$[Eclipse下载页面] 选择下载Eclipse发行版。
解压所下载的文件，然后您就可以用Eclipse目录中的Eclipse文件启动了。
在本指南的进一步介绍中，有一节介绍如何 <<eclipseDesignerInstallation,安装Eclipse Designer插件>> 。

[[reporting.problems]]

=== 报告问题

我们希望开发人员在报告或询问任何问题之前已经阅读了 link:$$http://www.catb.org/~esr/faqs/smart-questions.html$$[如何以明智的方式提出问题] 。

阅读完成后，您可以在 link:$$https://forum.flowable.org$$[用户论坛] 上发布关于增强功能的问题、评论或建议，并在我们的 link:$$https://github.com/flowable/flowable-engine/issues$$[Github问题跟踪程序] 中为bug创建issues。

[[experimental]]

=== 实验特征

标有 *[EXPERIMENTAL]* 的部分是不稳定的。

所有在包名中具有 +.impl.+ 的类，是内部实现类，也不能以任何方式被认为是稳定的或有保证的。
但是，如果用户指南提到任何类是作为配置值的，那么它们是受支持的，并且可以被认为是稳定的。

[[internal]]

=== 内部实现类

在JAR文件中，包名中含有 +.impl.+ 的所有类（例如 ++org.flowable.engine.impl.db++ ）是实现类，这些类应该只考虑在内部使用。
在实现类或接口上不提供稳定性保证。

=== 版本控制策略

版本号是使用标准的三个整数来表示：*MAJOR.MINOR.MICRO* 。

其目的是 *MAJOR* 版本用于核心引擎的演进。*MINOR* 版本用于新功能和新API。*MICRO* 版本用于错误修复和改进。

一般来说，对于所有非内部实现类，Flowable 尝试在 *MINOR* 和 *MICRO* 版本中保持 "源代码兼容" 。
我们定义 "源代码兼容" 是指应用程序将继续构建而不会出错，并且语义保持不变。
Flowable 还试图在 *MINOR* 版本和 *MICRO* 版本中保持 "二进制兼容" 。
我们定义 "二进制兼容" 是指这个新版本的 Flowable 可以作为JAR替换掉到编译后的应用程序中，并继续正常运行。


如果在 *MINOR* 版本中API发生了更改，则策略就是在其中保留向后兼容的版本，并用 _@Deprecated_ 标注。
这样这个API在随后两个 *MINOR* 版本后将被删除。
